# Generated by Django 3.0.3 on 2020-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerceApp', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
